### ISSUE TITLE
Inertia distribution channels

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#143]
Right now CLI releases are available only from the Releases page - could we set up distributions on services like [Homebrew](https://brew.sh)?

**Comment by iKevinY** [comment]
If you plan on trying to release on Homebrew, I can help out (I've worked on getting a few different formulae into the main tap). Note that they have some [guidelines](https://docs.brew.sh/Acceptable-Formulae) on submitting new formulae, requiring that the software in question not be "too obscure".

**Comment by bobheadxi** [comment]
Never really thought Homebrew had a submission process but I guess it makes sense.

Hopefully we don't fall under "too obscure" 😅 The guideline for reference:

> The software in question must:
be maintained (e.g. upstream is still making new releases)
be known
be stable (e.g. not declared “unstable” or “beta” by upstream)
be used
have a homepage
We will reject formulae that seem too obscure, partly because they won’t get maintained and partly because we have to draw the line somewhere.

Probably best to leave this as a future nice-to-have and put it on the backburner for now, thanks @iKevinY !

**Comment by iKevinY** [comment]
Actually, one really nice part about Homebrew is that it supports [third-party taps](https://docs.brew.sh/Taps), which are essentially opt-in repositories for formulae. It would be cool to maintain a "UBC Launch Pad" tap, to allow easy installation of all of Launch Pad's projects (including Inertia)!

**Comment by bobheadxi** [comment]
A UBC Launch Pad tap would actually be super neat! 🤔  paging @bfbachmann
