### ISSUE TITLE
User Expectations

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/inertia#15]
1. User installs inertia locally, user runs `inertia init`.
   + Alternatively, user ssh login, user install `inertia`, user run `inertia init`.
2. User opens port on VPS.
    + Can't avoid, need for server-daemon design choice (see #12).
3. User copy-paste public deploy key to GitHub.
   + Can avoid with oauth GitHub login or by logging into github thru inertia (see #14)
4. User copy-paste webhook URL to GitHub.
   + Maybe can avoid later with oauth GitHub login.

**Comment by bobheadxi** [comment]
Closing to move discussion to more specific tickets (ie #96 )
