### ISSUE TITLE
Docker bootstrapping fails on `inertia [VPS] init`

### ISSUE THREAD

**Issue by iKevinY** [ubclaunchpad/inertia#153]
I tried running `inertia $VPS init` and got the following error:

```bash
$ inertia <vps> init
Setting up remote <vps> at <remote>
>> Step 1/4: Installing docker...
bash: line 30: !(hash docker 2>/dev/null): No such file or directory
Failed to start docker.service: Unit docker.service not found.

FATA[0003] Process exited with status 5
```

The problem is that [`!(hash docker 2>/dev/null)`](https://github.com/ubclaunchpad/inertia/blob/72733b74a252a054478e9212caf8f6e193264e6b/client/bootstrap/docker.sh#L31) is actually doing some strange pseudo-`ls` 🤔:

```
$ ls
$ echo !(hash docker 2>/dev/null)
!(hash docker 2>/dev/null)
$ touch a.txt
$ echo !(hash docker 2>/dev/null)
a.txt
$ touch b.txt
$ echo !(hash docker 2>/dev/null)
a.txt b.txt
```

Since we do an early exit when Docker is already installed here, I think the problematic conditional can just be removed altogether?

https://github.com/ubclaunchpad/inertia/blob/72733b74a252a054478e9212caf8f6e193264e6b/client/bootstrap/docker.sh#L13-L15

**Comment by bobheadxi** [comment]
😱 Thats very interesting - I never looked to deeply into how this particular script works. I believe the original author of that marvellous hack is @chadlagore 🤔 Maybe he has something to point out here?

We haven't run into this issue on the platforms we test for - what VPS are you using when you encounter this bug?

**Comment by bobheadxi** [comment]
Also thanks in advance for putting in a fix if you do, since I notice you've assigned yourself 🥇

**Comment by iKevinY** [comment]
> what VPS are you using when you encounter this bug?

This was on a pretty standard Ubuntu 16.04 installation running on Google Compute Engine.

**Comment by chadlagore** [comment]
Do I get any points for hedging? :joy:

https://github.com/ubclaunchpad/inertia/blob/72733b74a252a054478e9212caf8f6e193264e6b/client/bootstrap/docker.sh#L4

Nice find @iKevinY. This was early days when we were trying to use the docker CLI to manage our containers. In reality `hash docker 2>/dev/null` is the wrong check now, something like this might make more sense?

```bash
if [ ! -e /var/run/docker.sock ]; then
        # Do install.
fi;
```

**Comment by chadlagore** [comment]
I agree, we can exit early, since the check already took place. I am interested in why its breaking though 🤔

**Comment by iKevinY** [comment]
To make things even more confusing, I grabbed the script manually and ran it on the machine directly, and it seemed to work fine… 🤔

**Comment by chadlagore** [comment]
Don't mind me 🙄

**Comment by iKevinY** [comment]
> In reality `hash docker 2>/dev/null` is the wrong check now, something like this might make more sense?

I can make this change in #154 if you think it's the proper check.

**Comment by chadlagore** [comment]
`hash docker 2>/dev/null` is fine for now I think. It will at least ensure the binary exists, which we may still use somewhere... I think you have the right fix in #154. @bobheadxi may have some other thoughts 💭

**Comment by bobheadxi** [comment]
> It will at least ensure the binary exists

Can the socket exist without the binary? 😮

**Comment by chadlagore** [comment]
Sure `sudo rm -rf $(which docker)` :joy:

**Comment by bobheadxi** [comment]
WELL that's a bit of an edge case isn't it haha

I don't think Docker works without its daemon though - we still have to [spin up the Docker daemon](https://github.com/ubclaunchpad/inertia/blob/master/client/bootstrap/docker.sh#L48), and it's a pretty integral part to how Docker works (read once that it's a bit of a controversial design decision) 🤔

**Comment by chadlagore** [comment]
Agreed :+1:
