### ISSUE TITLE
Auto-binarize Bootstrapping Scripts

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/inertia#155]
# 💭Auto-binarize Bootstrap Scripts

Right now if you change the bash scripts, in the `bootstrap` folder, you need to do this extra step of running `make bootstrap`.

Essentially we need to turn the shell scripts into the `bootstrap.go` source so that they can be compiled into the inertia binary. This is inconvenient and unintuitive for people making changes to the shell scripts. When this isn't done, happily our test suite catches it, but the travis build fails.

## :bulb: Ideas to Automate This (In Increasing Level of Terribleness)

1. Can we run `go-bindata` somehow during the `go build` step?
2. Can we run `go-bindata` as a [git pre-commit hook](https://githooks.com/)?
3. Can CI help us? I can't think of how to do this unless we allow Travis to commit to the feature branch, which sounds terrible.

**Comment by bobheadxi** [comment]
Hmm, I brought up a few points [here](https://github.com/ubclaunchpad/inertia/pull/154#issuecomment-378810503) against this but in summary:

- `make bootstrap` will actually modify `bootstrap.go` even if the scripts have not been modified - there's a little hash thing near the top that changes. Having this as a `pre-commit` hook will mean every single commit has a change to `bootstrap.go` 😢 

- It could feasibly be part of the `build` steps of our Makefiles, but the point above still stands... not sure how I feel about having commits include unnecessary changes to `bootstrap.go` 🤔 

**Most importantly**, however, is that `go-bindata` is actually dead and the original author gone (#76) 💀 Last I checked, no significant community has showed up to continue maintaining the project, so we should already be looking into an alternative anyway

**Comment by chadlagore** [comment]
Agreed, there might be another approach entirely.

**Comment by chadlagore** [comment]
Closing - look for another package (#76)
