### ISSUE TITLE
Image pruning

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#158]
`inertia $VPS prune`, since it seems like space can get quite bloated

Alternatively, prune periodically and optimize disk usage on builds where possible

**Comment by bobheadxi** [comment]
Probably prune image after deploy

Images to avoid:
- docker-compose
- herokuish

**Comment by rogermyang** [comment]
https://github.com/ubclaunchpad/inertia/blob/master/daemon/inertia/project/docker.go#L85

**Comment by bobheadxi** [comment]
Unassigning @rogermyang so he can focus on #243
