### ISSUE TITLE
Wireframe Inertia Web design

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#160]
The plan for v0.2.0 is to just have a super simple, barebones Inertia Web just to show that it works (#137, #134) 

The current state of the web app can be seen in this PR: #175
 
At some point, however, we probably want a nicer design and look wireframed and implemented.

## Initial features

- Log in + log out
- Logs + switch between containers
- Check on state of app
    - repo status: project name, commit, commit message, etc
    - build status: is project running? is it currently building? is in currently deploying?
- Deploy + shut down project (admins only)
- Add users (admins only)

**Comment by bobheadxi** [comment]
Interesting: https://github.com/zeit/next.js

**Comment by PiggySpeed** [comment]
I've seen zeit before, but I haven't tried it out myself.

They suggest avoiding CSS/LESS/SASS-based styling. If you still want it, you'll need to install an extra plugin.

I'm not quite convinced that it's worth using it at the cost of an extra dependency or two. It also seems like something that will be hard to change/remove once you start using it.

**Comment by bobheadxi** [comment]
Good point 👍

**Comment by asitu** [comment]
Review the wireframes please! https://projects.invisionapp.com/share/PBKNYUOVMHC#/screens/302194281
Login page is work in progress

**Comment by bobheadxi** [comment]
Looks good to me!

**Comment by bobheadxi** [comment]
I've added your link to the wiki here: https://github.com/ubclaunchpad/inertia/wiki/Web-App-Architecture

**Comment by bobheadxi** [comment]
Closing this as completed now - see #206 for ticket tracking implementation. Good work @asitu!
