### ISSUE TITLE
Standardize GET requests

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#176]
Well TIL that we shouldn't use Bodies with `GET` requests. Go's `client.Do()` doesn't complain, but Inertia Web complains if you `GET` with a `Body` 😢 

Looks like GET requests should have their options in the URL. This might actually work out in our favour, simplifying the `DaemonRequest` struct

Daemon endpoints will need to be update to use `url.Query()`

**Comment by PiggySpeed** [comment]
@bobheadxi  can I take a crack at this?
