### ISSUE TITLE
Call the directory that inertia puts stuff in (on the remote VPS) `inertia` instead of `project`

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/inertia#182]

**Comment by bobheadxi** [comment]
This does mean there will be a `.inertia` (user credentials, SSL certs, etc) and `inertia` folder, though I suppose that's pretty harmless 👍

**Comment by jordanschalm** [comment]
Could also do a root `inertia` folder and subfolders `project` and `config`
