### ISSUE TITLE
Secret management

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/inertia#183]
Some way to manage secrets. I usually use a `.env` file that isn’t version-controlled and the `env_file` option in docker-compose, so won’t be part of the build when pulling from GH with inertia.

Discussion whether or not this is in scope is warranted.

**Comment by bobheadxi** [comment]
It definitely is within scope! I think this is a dupe of #89

Not too sure about how to implement it though - there's [a rather stale branch up](https://github.com/ubclaunchpad/inertia/tree/rob/%2389-env-options) where I'm setting up the ability to `scp` a file (pressumably `.env`) over to the remote and as you mention use the `docker-compose` option, but wonder if theres a more universal way to set ENV vars inside containers from outside (so this will work for our other build options)

thoughts?

**Comment by jordanschalm** [comment]
Yes, you're right, didn't see #89. Closing this... 😅
