### ISSUE TITLE
Add favico

### ISSUE THREAD

**Issue by PiggySpeed** [ubclaunchpad/inertia#197]
Design and use an awesome favicon so that I don't have to keep looking at this.

<img width="517" alt="screen shot 2018-05-12 at 12 32 17 pm" src="https://user-images.githubusercontent.com/9895090/39960925-8be07a08-55e0-11e8-898b-46cfc318c3e6.png">

**Comment by bobheadxi** [comment]
What is this exactly?

**Comment by PiggySpeed** [comment]
@bobheadxi  It's the little icon for your webpage:
<img width="106" alt="screen shot 2018-05-13 at 3 44 12 pm" src="https://user-images.githubusercontent.com/9895090/39972428-9d256d52-56c4-11e8-84f0-929feab1c178.png">

**Comment by bobheadxi** [comment]
This will include a redraw of the current Gopher.

**Comment by bobheadxi** [comment]
@asitu do you mind looking into this? 😋

**Comment by asitu** [comment]
Inertia favicon could be as simple as just having the gopher!!
<img width="110" alt="screenshot 2018-06-23 23 10 27" src="https://user-images.githubusercontent.com/26077705/41816457-a7cf9732-773a-11e8-9ec1-91dba13417e0.png">

**Comment by bobheadxi** [comment]
That would work! We'll have to set up the gopher properly in the favico formats - I think bumper ended up with tons of different versions of their icon, though I'm not sure if that's **supposed** to be the case haha

https://github.com/ubclaunchpad/bumper/tree/master/client/public

<img width="483" alt="image" src="https://user-images.githubusercontent.com/23356519/41816482-1a742294-773b-11e8-89a3-aba071dbb07f.png">

**Comment by bobheadxi** [comment]
the more the merrier 😉

**Comment by asitu** [comment]
favicon.ico is squished 🙃

<img width="66" alt="screen shot 2018-07-28 at 3 30 39 pm" src="https://user-images.githubusercontent.com/26077705/43361098-4e8ff6b0-927b-11e8-8753-d55a3cd65410.png">

**Comment by asitu** [comment]
The more simple the favicon is, the better it looks on browser. The full body image is too detailed and it loses its details in a small image. So, an enlarged head looks recognizable from afar. 
What do you think? 

<img width="104" alt="screen shot 2018-07-28 at 7 44 23 pm" src="https://user-images.githubusercontent.com/26077705/43362438-05a001f6-929f-11e8-94a1-d8870a80adec.png">

**Comment by bobheadxi** [comment]
I love it hahah

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
