### ISSUE TITLE
Test and fix v0.4.0-rc1

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#202]
Lots of big changes and refactoring, and merging was a mess. Was too lazy to test thoroughly - need to verify changes work so far. Still a little ways off from a proper v0.4.0 though.

Need to verify:
- [ ] that heavily reworked `client` package works as expected
- [ ] the new build and deploy works on real projects - unsure what consequences building an image while container is still active is, since our tests don't actual verify if code changes will build (maybe thats something we need to change?)
- [ ] setting config functions from the CLI (#111) works as expected in every case
- [ ] the new defaults (ports, etc) don't cause any problems

The fact that we even have to do this probably indicates I follow awful practices and am a lazy bum, but oh well 🐛 

The binaries are available [here](https://github.com/ubclaunchpad/inertia/releases/tag/v0.4.0-rc1) - I don't think I will be updating homebrew for these guys

Please report bugs in this ticket.

**Comment by bobheadxi** [comment]
Brian suggested some nice resources for setting up a real remote VPS for testing:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EC2_GetStarted.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html

**Comment by brian-nguyen** [comment]
Not able to get my project set up :(
![image](https://user-images.githubusercontent.com/11564004/40276415-5dc1eba0-5bbe-11e8-9a2d-ee1fa7490999.png)

**Comment by bobheadxi** [comment]
YEah it seems super broken, definitely needs work :(

**Comment by bobheadxi** [comment]
Known issues:

- [ ] `"There does not appear to be a remote with this name."` (fixed in 4156e908802fde01882325a91eeb9a706413e758)
