### ISSUE TITLE
Expose stuff for webhooks

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#218]
https://developer.github.com/webhooks/configuring/

Either update CONTRIBUTING.md for setting up ngrok or https://github.com/localtunnel/localtunnel, or update the start_test_vps script to do it, or both

**Comment by bobheadxi** [comment]
paging @brian-nguyen in case he works it out

**Comment by brian-nguyen** [comment]
After playing around with both ngrok and localtunnel, I think there might be some conflict with Inertia HTTPS. Might have to do with the self-signed certificate? I got 502 Bad Gateway when using ngrok and accessing the tunnel URL. I switched the daemon over to use a plain old HTTP server instead and both ngrok and localtunnel worked.

**Comment by brian-nguyen** [comment]
After attaching to logs:
![image](https://user-images.githubusercontent.com/11564004/40816183-4b5f23ce-6500-11e8-9821-38be6d9087f5.png)

**Comment by bobheadxi** [comment]
One possibility is that you might need to explicitly disable the TLS check - in the client, we do this:

```go
func buildHTTPSClient() *http.Client {
	// Make HTTPS request
	tr := &http.Transport{
		// Our certificates are self-signed, so will raise
		// a warning - currently, we ask our client to ignore
		// this warning.
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}
	return &http.Client{Transport: tr}
}
```

if ngrok is forwarding traffic as HTTP, surely there's a way to forward it as HTTPS? I also wonder if we should set up something in the daemon to automatically redirect HTTP traffic to HTTPS.

**Comment by brian-nguyen** [comment]
They do but it's on a paid tier 😭 I'm actually on the redirect right now! I'll continue to update

**Comment by bobheadxi** [comment]
@brian-nguyen do you think you could write a script for this? 🙏

**Comment by brian-nguyen** [comment]
Requirements for the script? Is it just automatically run that ngrok command when the testvps starts?

**Comment by bobheadxi** [comment]
It would probably be a separate `make` command so that it's more explicit

but if the webhook doesn't work... it might be a better idea to find/build a small utility to fire "fake" webhooks events

**Comment by brian-nguyen** [comment]
For the ngrok setup to work, I'd need to add the HTTP server too. Is that still something you want?

**Comment by bobheadxi** [comment]
I feel we can close this ticket in favour of other ways of testing webhooks (unit tests) - I’m not sure if integration testing is worth the overhead :( esp because webhooks are usually well documented and pretty specific

What do you think?

**Comment by brian-nguyen** [comment]
I agree!
