### ISSUE TITLE
Dockerize Testing Environment

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/inertia#23]
A lot of our initialization code does some small file system changes. This may be something we want to dockerize in order to test properly. Discuss?

```
container1 (fake local, file system changes) <---- ssh pipe ----> container2 (fake remote, accepts ssh commands)
```

**Comment by chadlagore** [comment]
Run this as integration test on travis for all OS we want to support.

**Comment by chadlagore** [comment]
From #40:

> For development, we're currently using an actual host on gcloud or somewhere. We should write a script that starts a container that we can use as if it were a remote, enable SSH access to it, create a PEM, output login credentials etc, etc. It will save development time and $$.

> Much like @bobheadxi's testing strategy here: #30

**Comment by bobheadxi** [comment]
For my own reference:
https://github.com/concourse/concourse/issues/927#issuecomment-286067554
