### ISSUE TITLE
Inertia Web - Wireframe Implementation

### ISSUE THREAD

**Issue by PiggySpeed** [ubclaunchpad/inertia#248]
This is the epic for the wireframe implementation of Inertia Web, updated from #206, which is now closed as a duplicate. None of these tasks require use of redux until we start working with API calls. For the time being, feel free to use hard-coded mock data to support your UI elements. All of our work here should go through approval by @asitu.

There are dependencies between the tasks. We can minimize the effects of this by completing the tasks in this order.

This is not comprehensive of all components that we will require for our UI. I've listed only the major ones.

Global Styles - SASS #240 
Component - IconHeader #249 
Component - Table #242 
Component - Terminal View #243 
Component - NavBar #241 
Component - Footer #250 
Page - Dashboard #244 
Page - Containers #245 
Page - Team #246 
Page - Settings #247 

Priorities are listed from top-to-bottom.

These designs should all be based on the wireframe from #160, which can be seen here: https://projects.invisionapp.com/share/PBKNYUOVMHC#/screens/302194281

**Comment by bobheadxi** [comment]
Updated ticket description for some stuff that was included in #206 which is now closed as a duplicate, and added this ticket to the Inertia Web epic (#204)

**Comment by asitu** [comment]
Here's a pdf version of the wireframes - static images in case you don't to interact with the prototype :) 
[https://app.zenhub.com/files/112870404/787a4247-52ba-42b1-97c5-6dfbebf6f4cf/download](https://app.zenhub.com/files/112870404/787a4247-52ba-42b1-97c5-6dfbebf6f4cf/download)
