### ISSUE TITLE
`inertia provision ec2 [name]`

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#261]
Provision ECS instance and set it up for Inertia

**Comment by bobheadxi** [comment]
This might tie into #168 as well

**Comment by iKevinY** [comment]
#144 🙃

**Comment by bobheadxi** [comment]
Reopened! Starting to think this might be a cool feature to have:

```bash
$ inertia provision ec2 my_vps
$ inertia my_vps up
```

See #265, thanks for the remidner 😄
