### ISSUE TITLE
CONTRIBUTING.md Suggestions

### ISSUE THREAD

**Issue by leesw98** [ubclaunchpad/inertia#298]
In no particular order:
- The line that notes `Make sure all of the above are installed before running:` should also note that Docker should be running
- Noting the versions would be nice. They don't have to be exact. Something along the line of `Node.js 8.x` is good enough. I had `10.x` installed and was confused for a minute with npm complaining.
- Adding a comment about pathing the executable would be nice. I have added the following in my `.bashrc`/`.bash_profile`:
```bash
# go-lang
export PATH="$PATH:$HOME/go/bin"
export GOPATH=$HOME/go
export GOBIN=$HOME/go/bin
```
- The line that notes `If you make changes to the bootstrapping shell scripts in client/bootstrap/` probably means to say `client/scripts/`. There are few other places that also references `client/bootstrap/`.

**Sidenote:**
- After some screwing around I noticed this output:
```bash
[...]
scp -i ./test/keys/id_rsa \
		-o StrictHostKeyChecking=no \
		-o UserKnownHostsFile=/dev/null \
		-P 69 \
		./images/inertia-daemon-image \
		root@0.0.0.0:/daemon-image
Warning: Permanently added '[0.0.0.0]:69' (ECDSA) to the list of known hosts.
[...]
```
It would be nice to know the security implication of this. I couldn't find anything interesting/concerning. Just wondering if there are any.

Overall, everything seemed pretty forward or was a classic:fu:by me.

**Comment by bobheadxi** [comment]
> Something along the line of Node.js 8.x is good enough. I had 10.x installed and was confused for a minute with npm complaining.

What problems exactly did you have with node 10? I'm personally on node 10 and I haven't run into any issues (though I haven't been working much on the web app lately)

> Adding a comment about pathing the executable would be nice. I have added the following in my .bashrc/.bash_profile:

This should honestly be part of the Go install @_@ but yeah I'll add a note on that

> The line that notes If you make changes to the bootstrapping shell scripts in client/bootstrap/ probably means to say client/scripts/. 

yes it does oops 😋 

> Warning: Permanently added '[0.0.0.0]:69' (ECDSA) to the list of known hosts.

It means that you trust your own computer @ port 69, which IMO is a safe enough assumption. I couldn't find anything interesting about back when I first set this up (way back in the v0.1.0 days), but I'm not confident enough to claim anything about the security of this... but it should be fine.
