### ISSUE TITLE
Inertia web set environment variables

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#320]
In settings, users should be able to set [environment variables](https://en.wikipedia.org/wiki/Environment_variable)

A variable is:

```
NAME=VALUE
```

The UI will need:

- variable list (name, value) and an icon to delete each
- input to add new values (provide a name, a value, and a checkbox (`encrypt`))

To do:
- [ ] design @asitu 
- [ ] implementation

**Comment by asitu** [comment]
Settings UI using environment variables: 
![settings](https://user-images.githubusercontent.com/26077705/42740504-47a9f508-885d-11e8-8d4e-9f6078e65516.png)

Edit mode includes 
- checkboxes
- "Action" column to delete rows
- Cancel and Save buttons

![settings-input](https://user-images.githubusercontent.com/26077705/42741950-7f876bb4-886b-11e8-8d3a-751a1f8cfcb1.png)

How is this used in the settings features - shutting down project, themes, etc?

**Comment by bobheadxi** [comment]
Edit mode looks great! There should be something to allow users to `Add` new variables as well

**Comment by asitu** [comment]
Designed 3 different versions of the user experience:
1. User clicks on Add button and leads to the edit mode page 
2. User inputs new variable at the bottom edit section, and the variable is added to the top section
3. User clicks on the Add button and a new row is added at the bottom where user inputs values.
<img width="744" alt="screen shot 2018-07-16 at 6 47 28 pm" src="https://user-images.githubusercontent.com/26077705/42792135-cd36377e-8928-11e8-893a-7f6ffe724499.png">

**Comment by bobheadxi** [comment]
I like the 3rd one 🎉  the second one looks nice, but as we add more settings, having multiple sections just for environment variables might get confusing
