### ISSUE TITLE
Login Page Web Design & Implementation

### ISSUE THREAD

**Issue by asitu** [ubclaunchpad/inertia#329]
Design & Implement login page.

Design: 
- Color Scheme
- Animated gopher inside a rocket

**Comment by bobheadxi** [comment]
> Animated gopher inside a rocket

😍

**Comment by asitu** [comment]
![login](https://user-images.githubusercontent.com/26077705/44756597-385fd180-aae0-11e8-91b0-85c5bc63e4ba.png)

Feedback on illustration? @zhulia96 @bobheadxi

**Comment by bobheadxi** [comment]
I love it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bobheadxi** [comment]
Is the “login” text needed? I think just “inertia” and the inputs should be enough

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
