### ISSUE TITLE
Autobind decorator

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#375]
> bind is hideously slow and should be avoided whenever possible (90% slower).

https://github.com/nwhacks/nwhacks2019/pull/11#discussion_r200822229

> Seems like @autoBind is the most performant way to do this overall. Though, the performance difference is probably negligible anyways.

https://github.com/nwhacks/nwhacks2019/pull/14#discussion_r200828602

Another interesting comment, demonstrating the implementation differences of each:

https://github.com/nwhacks/nwhacks2019/pull/14#issuecomment-403261571

**Comment by PiggySpeed** [comment]
Reposting one of the references here for easy access: [Link](https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1)

Haven't thought about this before, will investigate further. Great discussion going on there.
