### ISSUE TITLE
go mod

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#395]
Preliminary support for go modules (formerly vgo) has landed https://blog.golang.org/go1.11

Look into if this is already in a usable state for inertia

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by suujia** [comment]
`404 page not found`

**Comment by bobheadxi** [comment]
My bad, fixed it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bobheadxi** [comment]
Done since #619
