### ISSUE TITLE
Replace box env encryption with crypto/symmetric.go

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#437]
See #436 

The (bad 😢) box implementation: https://github.com/ubclaunchpad/inertia/blob/master/daemon/inertiad/crypto/box.go

**Comment by dreamer-89** [comment]
@bobheadxi : Please assign this issue to me.

**Comment by bobheadxi** [comment]
Awesome, thanks @dreamer-89! Feel free to ping this ticket if you run into any issues.

**Comment by bobheadxi** [comment]
Can't seem to assign to non-collaborators, but I'll mark this issue as in-progress

**Comment by dreamer-89** [comment]
Thanks @bobheadxi  :)

**Comment by dreamer-89** [comment]
@bobheadxi : Why do we want to replace box.go public key cryptography with symmetric.go private key cryptography ? Why are we saying that box.go is bad implementation. I see box.go as a measure of public key cryptography with authentication.

**Comment by dreamer-89** [comment]
On running unit tests in data_test.go, I am getting below errors:
`# github.com/ubclaunchpad/inertia/daemon/inertiad/build
/Users/zomato/go/src/github.com/ubclaunchpad/inertia/daemon/inertiad/build/builder.go:244:10: cannot use p (type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".Port) as type "github.com/docker/go-connections/nat".Port in map index
/Users/zomato/go/src/github.com/ubclaunchpad/inertia/daemon/inertiad/build/builder.go:256:4: cannot use portMap (type "github.com/docker/go-connections/nat".PortMap) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in field value
FAIL	github.com/ubclaunchpad/inertia/daemon/inertiad/project [build failed]`

**Comment by dreamer-89** [comment]
@bobheadxi : Please advise how should I resolve these errors.

**Comment by bobheadxi** [comment]
Did you run `dep ensure`? It looks like instead of using dependencies in your `vendor` directory, Go is attempting to pull dependencies from your GOPATH

**Comment by dreamer-89** [comment]
@bobheadxi : Thanks, running dep ensure removed errors while running tests

**Comment by dreamer-89** [comment]
@bobheadxi : Now, working on it.

**Comment by dreamer-89** [comment]
@bobheadxi : Please review: https://github.com/ubclaunchpad/inertia/pull/471

Please let me know regarding testing. Does it need unit tests, if yes, please share an example.

**Comment by dreamer-89** [comment]
@bobheadxi : Changes has been done as suggested.
Thanks a lot for your patience and guidance. Please let me know if I can work on other go specific issues as well.

**Comment by bobheadxi** [comment]
Thanks a lot for that PR @dreamer-89 ! If you interested, there's another ticket that no one's working on yet that I'm hoping to resolve before the next release: #458
