### ISSUE TITLE
Cannot log out from SSH session

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/inertia#441]
**Describe the bug**
Logging out from an SSH session with an Inertia remote (e.g. with the `exit` command) will not actually log the user out, and then have to ^C to get back to their own shell.

**To Reproduce**
1. Create or connect to a remote
2. SSH into the remote
3. `exit`
4. SSH session will not logout

**Expected behavior**
A clear and concise description of what you expected to happen:
`exit` command will exit SSH session and return user to their local shell.

**Comment by bobheadxi** [comment]
## Notes

To handle ctrl-c, you can intercept signals in Go: https://sourcegraph.com/github.com/ubclaunchpad/pinpoint/-/blob/gateway/cmd/run.go#L63

**Comment by bobheadxi** [comment]
Although @rwblickhan notes it would probably to just drop into an SSH subprocess, with appropriate args provided from inertia config
