### ISSUE TITLE
cmd: bash autocompletions

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/inertia#443]
**Is your feature request related to a problem? Please describe.**
Inertia requires a lot of typing to interact with, especially when using `inertia [remote]`-related subcommands, as there are no shell completions as far as I can tell.

**Describe the solution you'd like**
Inertia should have autocomplete scripts for bash and preferably zsh as well, a la [git_completion.bash](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash), and in particular should have support for completing remote names and subcommands if possible.

**Describe alternatives you've considered**
Inertia could continue to lack a bash completion script, and users could continue to be frustrated 😃

**Additional context**
According to @bobheadxi Inertia uses the Cobra command line parsing library, which can [generate a bash completion script](https://github.com/spf13/cobra/blob/master/bash_completions.md), although it seems to require a fair amount of work on the part of the developers.

**Comment by bobheadxi** [comment]
Experimental:

```go
package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

func init() {
	completionCmd.Flags().String("file", "", "write bash completion to a file")
	completionCmd.Flags().Bool("zsh", false, "generate completions for zsh")
	Root.AddCommand(completionCmd)
}

// completionCmd represents the completion command
// Sourced from: https://github.com/spf13/cobra/blob/master/bash_completions.md
var completionCmd = &cobra.Command{
	Use:   "completion",
	Short: "Generate bash completion scripts",
	Long: `To load completion run:

. <(inertia completion)

To configure your bash shell to load completions for each session add to your bashrc:

# ~/.bashrc or ~/.profile
. <(inertia completion)
`,
	Run: func(cmd *cobra.Command, args []string) {
		var zsh, _ = cmd.Flags().GetBool("zsh")
		if f, _ := cmd.Flags().GetString("file"); f != "" {
			if zsh {
				Root.GenZshCompletionFile(f)
			} else {
				Root.GenBashCompletionFile(f)
			}
		} else {
			if zsh {
				Root.GenZshCompletion(os.Stdout)
			} else {
				Root.GenBashCompletion(os.Stdout)
			}
		}
	},
}
```

doesn't work:

```sh
❯ source <(inertia completion --zsh)
_arguments:comparguments:319: can only be called from completion function
_arguments:comparguments:319: can only be called from completion function
```

**Comment by bobheadxi** [comment]
We might want to add this to the `inertia-docgen` tool: https://github.com/ubclaunchpad/inertia/blob/master/contrib/inertia-docgen/main.go
