### ISSUE TITLE
No notification that webhook content type should be JSON

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/inertia#444]
**Describe the bug**
Github defaults to x-www-form-urlencoded Content-Type for webhooks, but Inertia requires that Content-Type be set to JSON. This isn't mentioned in the README nor in the output from `inertia $VPS_NAME init`, and if the user does not know this, it will cause continuous deployment to fail silently.

**To Reproduce**
1. Init a new remote

Output:
```bash
>> GitHub WebHook URL (add to https://www.github.com/rocket2.0/settings/hooks/new):
Address:  https://ec2-54-81-138-232.compute-1.amazonaws.com:4303/webhook
Secret:   agFZgO0mSgM4W_QGd39_8XQLvBLA0ejIXnIbhsh5jLc=

Note that you will have to disable SSH verification in your webhook
settings - Inertia uses self-signed certificates that GitHub won't
be able to verify.
```

**Expected behavior**
Message should mention that JSON Content-Type is required if using Github webhook.

**Additional context**
Adding support for form-encoded Github webhooks is in ticket #369.

**Comment by bobheadxi** [comment]
The code for this output is here: https://github.com/ubclaunchpad/inertia/blob/master/client/client.go#L119
