### ISSUE TITLE
Don't delete users after 3 failed logins

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/inertia#460]
Deleting user accounts after 3 failed logins is a pretty poor experience, and it leaves Inertia users open to DOS attacks. As an attacker, I can easily get Inertia to delete someone's account by simply executing 3 failed login attempts.

Instead, I propose using exponential backoff. Maybe start by locking the user out for a few min after 10 failed attempts, then a few hours.

**Comment by bobheadxi** [comment]
What would you rather the behaviour be?

I think it’s fine, because the usernames shouldn’t be easy to procure anyway

**Comment by bfbachmann** [comment]
See my description above for info on how to fix it. Exponential backoff is the most common and simplest approach for this.

**Comment by bfbachmann** [comment]
I'll also note that literally any user can view any other user's username using the `ls` command.

**Comment by bobheadxi** [comment]
I guess the model was originally based on the assumption that you would only be a user if you are trusted - only the original admin can create users

But I agree, exponential back off might be the way to go here

**Comment by bfbachmann** [comment]
@bobheadxi It was pointed out to us that having a rate limiting mechanism in place like exponential backoff just opens up the service to DOS attacks - if you know someone's account just try to long in as  them a few times and you lock them out for a while. As such we decided that rate limiting wasn't worth it. That being said, I still think it's worth not deleting users after any number of failed logins, since that's actually a much worse "DOS attack" than if someone were to take advantage of exponential backoff.

**Comment by bobheadxi** [comment]
Hm, should we just allow infinite attempts then?

**Comment by bobheadxi** [comment]
After discussing with @bfbachmann , decided we'll keep the current behaviour but bump the limit up to 10
