### ISSUE TITLE
Webhook deliveries time out

### ISSUE THREAD

**Issue by gbvivian** [ubclaunchpad/inertia#525]
for certain events it seems

![image](https://user-images.githubusercontent.com/17520798/51801260-2057bf80-21f0-11e9-9b3e-75b20f64eba3.png)

handshake also seems to be rejected

![image](https://user-images.githubusercontent.com/17520798/51801272-38c7da00-21f0-11e9-81f7-41fe4ca130dc.png)

**Comment by bobheadxi** [comment]
this probably happens because at some point during the webhook reworks we forgot to add support for `X-GitHub-Event ping`

**Comment by bobheadxi** [comment]
I'll resolve this once we land #528
