### ISSUE TITLE
cmd: "inertia remote login"

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#535]
We have an `inertia [remote] user login`, but we should add an `inertia remote login` as well to complement `inertia remote add` - the latter asks for a lot of SSH-specific information that a user using an account does not have to provide.

**Comment by yaoharry** [comment]
@bobheadxi 
Could you clarify again how `inertia [remote] user login` differs from `inertia remote login`? 

Additionally, would its input parameters be like this:
`inertia remote login [remote IP address]`, which would prompt for user and password for the remote?

**Comment by bobheadxi** [comment]
* `inertia [remote] user login`: given a *previously configured* remote, log in as a user
* `inertia remote login`: connect to an existing remote as a user, as an alternative to `inertia remote add`, which prompts for a lot of details that are more relevant to first-time setup than anything else

Input would probably be:

```
inertia remote login [remote_name] [address] [--user] [--totp]
```

if no user is provided, prompt for user when the command runs, and then prompt for password. `remote_name` would be what to call the remote after successfully connecting to it.

e.g.

```sh
$> inertia remote login existing_remote 123.456.789.101 --user bobheadxi
# ...
$> inertia existing_remote status
```

**Comment by yaoharry** [comment]
Would `inertia remote login [remote_name] [address] [--user] [--totp]` configure the remote for future logins? Or would it be more of a one time login?

Ex. Once `inertia remote login` is executed would `inertia [remote] user login` be able to be ran as it is now configured?

**Comment by bobheadxi** [comment]
yep `inertia [remote] user login` is unaffected (a user would need it to refresh their token, or switch users)
