### ISSUE TITLE
daemon: user reset invalidates the 'master' token

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#550]
try:

```
inertia [remote] user reset
inertia [remote] user ls
```

the last command will throw an error saying you are not an admin, even if the token originally was. this probably happens because `master` is a "user", and is cleared from the database on `reset`:

* how the master user is added: https://sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/daemon/inertiad/auth/users.go#L56
* how the database is deleted: https://sourcegraph.com/github.com/ubclaunchpad/inertia/-/blob/daemon/inertiad/auth/users.go#L76

the reset function will just need to create the master use again when it creates the bucket. we'll want some regression tests for this too

**Comment by bobheadxi** [comment]
This was accidentally tagged for closing in #555 oops

**Comment by kip-13** [comment]
I have been doing some research and with your suggestion the daemon still show an error:

```
> inertia local user ls
[error 401] session not found
```

So the another path could be in `endAllSessions()`
```go
func (h *PermissionsHandler) resetUsersHandler(w http.ResponseWriter, r *http.Request) {
	// Delete all users
	if err := h.users.Reset(); err != nil {
		render.Render(w, r, res.ErrInternalServer("failed to reset users and sessions", err))
		return
	}

	// Delete all sessions
	h.sessions.EndAllSessions()

	render.Render(w, r, res.MsgOK("user and session databases reset"))
}
```

What do you think ?

**Comment by bobheadxi** [comment]
ah, yeah - two ways that could be fixed:

* `EndAllSessions()` looks for and avoids removing sessions of the `master` token
* `inertia [remote] user reset` also includes a call to generate a new token. this is done in bootstrap using the [ssh client](https://sourcegraph.com/github.com/ubclaunchpad/inertia@d4c3a402db569000806280260f7148221c020c8c/-/blob/client/bootstrap/bootstrap.go#L74), so a similar thing could be done here, though that would mean a non-master user with admin permissions but without SSH access could really mess things up 😓 

imo the first approach here is probably best

**Comment by kip-13** [comment]
> though that would mean a non-master user with admin permissions but without SSH access could really mess things up

But now a non-master admin user could delete the master session:

```go
// endAllUserSessions removes all active sessions with given user
func (s *sessionManager) EndAllUserSessions(username string) {
	for id, claim := range s.internal {
		if claim.User == username {
			s.deleteSession(id)
		}
	}
}
```

So, maybe this is another necessary fix right ?

**Comment by bobheadxi** [comment]
yep fixing that is probably needed to resolve this bug

**Comment by kip-13** [comment]
My comment about the master session was bad, the master session isn't tracked:

https://github.com/ubclaunchpad/inertia/blob/d4c3a402db569000806280260f7148221c020c8c/daemon/inertiad/auth/sessions.go#L136-L139

So, I dont know why I received the error posted about the session not found. Maybe some mistake related to my test environment.

**Comment by kip-13** [comment]
This issue have 2 kinds of scopes: `daemon:`(tittle) and `cmd:`(label), which is correct to create the branch for PR ?

**Comment by bobheadxi** [comment]
Go with `daemon`! It seems like that's where the core of the issue is :)
