### ISSUE TITLE
docs: typo in daemon/inertiad/crypto/token.go

### ISSUE THREAD

**Issue by leesw98** [ubclaunchpad/inertia#564]
**Describe the bug**
Typo in https://github.com/ubclaunchpad/inertia/blob/master/daemon/inertiad/crypto/token.go#L38. I would do it myself but I am not in the team @bobheadxi 🤷‍♂️  

`mster -> master`

**Comment by bobheadxi** [comment]
@leesw98 could fork and PR, or even just edit in the GH interface 😋 good catch though
