### ISSUE TITLE
Secure client-server communication

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/inertia#59]
Right now the daemon sets up an HTTP (not HTTPS) listener. This makes the token authorization system vulnerable to replay attacks since the token is sent in the clear.

To fix: Use HTTPS exclusively. Maybe there's a way to generate a cert when creating a new remote, and informing the client-side to trust that cert?

**Comment by chadlagore** [comment]
+1 on this, not done in the first place out of pure ignorance. Must do :+1:.

**Comment by jordanschalm** [comment]
**References:**
* [generating certs](https://golang.org/src/crypto/tls/generate_cert.go)
* [listening on TLS](https://golang.org/pkg/net/http/#ListenAndServeTLS)

**Comment by bobheadxi** [comment]
More references:
- [automated certificates](https://godoc.org/golang.org/x/crypto/acme/autocert)
- [serving](https://blog.kowalczyk.info/article/Jl3G/https-for-free-in-go-with-little-help-of-lets-encrypt.html)
