### ISSUE TITLE
docker-compose volume mounts don't work

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/inertia#601]
**Describe the bug**
Mounting volumes via docker-compose doesn't work as expected when deploying with Inertia.

**Environment (please complete the following information):**
 - Client OS: macOS
 - VPS OS: Amazon Linux
 - Project Details: [Rocket 2](https://github.com/ubclaunchpad/rocket2)
 - Version: 0.5.1

**Additional context**
We'd like to mount volumes using docker-compose, so that nginx has access to configuration files and SSL certificates on the host machine. However, it appears that, due to the build process associated with Inertia, this does not work. We've tried mounting both `/etc/nginx/` and `$HOME/etc/nginx`. In the former case, when configured with:
```
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - /etc/letsencrypt
            - /usr/share/nginx/html
            - /etc/nginx
``` 
in `docker-compose.yml`, we get the following result with `docker inspect`:
```
"Mounts": [
            {
                "Type": "volume",
                "Name": "f2a300aa9221b7f4f5a1d9c0763cc66bca8256988f3a3cda15d384e474539c93",
                "Source": "/var/lib/docker/volumes/f2a300aa9221b7f4f5a1d9c0763cc66bca8256988f3a3cda15d384e474539c93/_data",
                "Destination": "/etc/letsencrypt",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "f493cbe3812ffd28a34866075253d66f93b1edf61a73602002533d3e9468b307",
                "Source": "/var/lib/docker/volumes/f493cbe3812ffd28a34866075253d66f93b1edf61a73602002533d3e9468b307/_data",
                "Destination": "/etc/nginx",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "aa520bf2eaeb0f1177946e4ad1e18bd63c507ab955b12ff48b8ad06d0a509fe6",
                "Source": "/var/lib/docker/volumes/aa520bf2eaeb0f1177946e4ad1e18bd63c507ab955b12ff48b8ad06d0a509fe6/_data",
                "Destination": "/usr/share/nginx/html",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ]
```
We see similar when `docker-compose.yml` has `${HOME}/etc/nginx` or `/home/ec2-user/etc/nginx`.

It may not be possible to provide this, but at the very least this behaviour should be added to the documentation somewhere - I had to take a look at the Inertia source code and contact @bobheadxi to figure out what was likely happening.

**Comment by rwblickhan** [comment]
Seems like this might be user error - as you may notice, I was doing:
```
volumes:
    - /etc/nginx
```
instead of
```
volumes:
    - /etc/nginx:/etc/nginx
```
so Docker was "helpfully" creating a new, empty volume on the container. It's still not working but it's likely not Inertia's fault - if I can get it working I'll go ahead and close this ticket. You may still want to double check that volume mounting really does work as expected however.

**Comment by bobheadxi** [comment]
@rwblickhan looks like you worked it out as of https://github.com/ubclaunchpad/rocket2/pull/257 - is this still an issue?

**Comment by rwblickhan** [comment]
Yep, doesn't seem like this is actually a problem. Closing.
