### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/inertia#8]
# Configuration Options

The following are some configuration parameters Inertia may have to accept:
* Whitelisted webhook URL(s) (we should only accept POST requests to a specific set
  of user-specified URLs).
* Repositories to build from
* Branches to build from for a given repo
* Events to build from (push, PR, etc.) for a given repo
* Secrets for secure communication and code-transfer

# Configuration Methods

### `yml` Config File

Pros
* Easy to implement

Cons
* User has to manually edit the config file over SSH or copy a new version
    over to their VPS every time they want to change config. They may also have
    to restart the daemon to load the new config, but we could implement some
    auto-refresh mechanism.

### Configuration over HTTP or some RPC

Pros
* If we're going to have a CLI that communicates with our daemon it makes
sense to design our daemon to accept remote config from the beginning anyway.
* Theoretically zero downtime for configuration changes because there is no
need to restard the daemon to load new config.

Cons
* Harder to implement.

### Hybrid of previous 2 options

Pros
* Sick

Cons
* It's the most work

**Comment by bobheadxi** [comment]
Closing since discussion has moved to more specific tickets (ie #67)
